CREATE TABLE GRAVADORA (
    ID_Gravadora INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Endereco VARCHAR(255),
    Telefone VARCHAR(20)
);

CREATE TABLE ESTILO (
    ID_Estilo INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE MUSICA (
    ID_Musica INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Duracao TIME,
    ID_Estilo INT NOT NULL,
    FOREIGN KEY (ID_Estilo) REFERENCES ESTILO(ID_Estilo)
);

CREATE TABLE DISCO_CD (
    ID_DiscoCD INT PRIMARY KEY AUTO_INCREMENT,
    Titulo VARCHAR(255) NOT NULL,
    DataLancamento DATE,
    Preco DECIMAL(10, 2),
    ID_Gravadora INT NOT NULL,
    FOREIGN KEY (ID_Gravadora) REFERENCES GRAVADORA(ID_Gravadora)
);

CREATE TABLE COMPOSITOR (
    ID_Compositor INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Nacionalidade VARCHAR(100)
);

CREATE TABLE INTERPRETE (
    ID_Interprete INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Nacionalidade VARCHAR(100)
);

CREATE TABLE DISCO_MUSICA (
    ID_DiscoCD INT NOT NULL,
    ID_Musica INT NOT NULL,
    Numero_Faixa INT,
    PRIMARY KEY (ID_DiscoCD, ID_Musica),
    FOREIGN KEY (ID_DiscoCD) REFERENCES DISCO_CD(ID_DiscoCD),
    FOREIGN KEY (ID_Musica) REFERENCES MUSICA(ID_Musica)
);

CREATE TABLE MUSICA_COMPOSITOR (
    ID_Musica INT NOT NULL,
    ID_Compositor INT NOT NULL,
    PRIMARY KEY (ID_Musica, ID_Compositor),
    FOREIGN KEY (ID_Musica) REFERENCES MUSICA(ID_Musica),
    FOREIGN KEY (ID_Compositor) REFERENCES COMPOSITOR(ID_Compositor)
);

CREATE TABLE MUSICA_INTERPRETE (
    ID_Musica INT NOT NULL,
    ID_Interprete INT NOT NULL,
    PRIMARY KEY (ID_Musica, ID_Interprete),
    FOREIGN KEY (ID_Musica) REFERENCES MUSICA(ID_Musica),
    FOREIGN KEY (ID_Interprete) REFERENCES INTERPRETE(ID_Interprete)
);