CREATE TABLE LOCALIDADE (
    ID_Localidade INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE ZONA_ELEITORAL (
    ID_Zona INT PRIMARY KEY AUTO_INCREMENT,
    Numero INT NOT NULL,
    ID_Localidade INT NOT NULL,
    UNIQUE (Numero, ID_Localidade),
    FOREIGN KEY (ID_Localidade) REFERENCES LOCALIDADE(ID_Localidade)
);

CREATE TABLE SECAO_ELEITORAL (
    ID_Secao INT PRIMARY KEY AUTO_INCREMENT,
    Numero INT NOT NULL,
    ID_Zona INT NOT NULL,
    UNIQUE (Numero, ID_Zona),
    FOREIGN KEY (ID_Zona) REFERENCES ZONA_ELEITORAL(ID_Zona)
);

CREATE TABLE PARTIDO_POLITICO (
    ID_Partido INT PRIMARY KEY AUTO_INCREMENT,
    Sigla VARCHAR(10) NOT NULL UNIQUE,
    Nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE CANDIDATO (
    ID_Candidato INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Numero INT UNIQUE,
    ID_Partido INT NOT NULL,
    FOREIGN KEY (ID_Partido) REFERENCES PARTIDO_POLITICO(ID_Partido)
);

CREATE TABLE ELEITOR (
    ID_Eleitor INT PRIMARY KEY AUTO_INCREMENT,
    TituloEleitoral VARCHAR(20) NOT NULL UNIQUE,
    Nome VARCHAR(255) NOT NULL,
    ID_Secao INT NOT NULL,
    FOREIGN KEY (ID_Secao) REFERENCES SECAO_ELEITORAL(ID_Secao)
);

CREATE TABLE VOTO (
    ID_Voto INT PRIMARY KEY AUTO_INCREMENT,
    ID_Secao INT NOT NULL,
    ID_Candidato INT,
    DataHoraVoto DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TipoVoto ENUM('Nominal', 'Branco', 'Nulo') NOT NULL,
    FOREIGN KEY (ID_Secao) REFERENCES SECAO_ELEITORAL(ID_Secao),
    FOREIGN KEY (ID_Candidato) REFERENCES