CREATE TABLE DEPARTAMENTO (
    ID_Departamento INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE CARGO (
    ID_Cargo INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL UNIQUE,
    Descricao TEXT
);

CREATE TABLE CONCURSO (
    ID_Concurso INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    DataInicio DATE,
    DataFim DATE
);

CREATE TABLE ETAPA (
    ID_Etapa INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Tipo ENUM('Classificatória', 'Eliminatória') NOT NULL,
    ID_Concurso INT NOT NULL,
    FOREIGN KEY (ID_Concurso) REFERENCES CONCURSO(ID_Concurso)
);

CREATE TABLE CANDIDATO (
    ID_Candidato INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) UNIQUE
);

CREATE TABLE INSCRICAO (
    ID_Inscricao INT PRIMARY KEY AUTO_INCREMENT,
    ID_Candidato INT NOT NULL,
    ID_Cargo INT NOT NULL,
    ID_Concurso INT NOT NULL,
    DataInscricao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (ID_Candidato, ID_Cargo, ID_Concurso),
    FOREIGN KEY (ID_Candidato) REFERENCES CANDIDATO(ID_Candidato),
    FOREIGN KEY (ID_Cargo) REFERENCES CARGO(ID_Cargo),
    FOREIGN KEY (ID_Concurso) REFERENCES CONCURSO(ID_Concurso)
);

CREATE TABLE RESULTADO (
    ID_Resultado INT PRIMARY KEY AUTO_INCREMENT,
    ID_Inscricao INT NOT NULL,
    ID_Etapa INT NOT NULL,
    Nota DECIMAL(5, 2),
    DataRealizacao DATE,
    UNIQUE (ID_Inscricao, ID_Etapa),
    FOREIGN KEY (ID_Inscricao) REFERENCES INSCRICAO(ID_Inscricao),
    FOREIGN KEY (ID_Etapa) REFERENCES ETAPA(ID_Etapa)
);
CREATE TABLE CARGO_DEPARTAMENTO (
    ID_Cargo INT NOT NULL,
    ID_Departamento INT NOT NULL,
    PRIMARY KEY (ID_Cargo, ID_Departamento),
    FOREIGN KEY (ID_Cargo) REFERENCES CARGO(ID_Cargo),
    FOREIGN KEY (ID_Departamento) REFERENCES DEPARTAMENTO(ID_Departamento)
);

CREATE TABLE CONCURSO_CARGO (
    ID_Concurso INT NOT NULL,
    ID_Cargo INT NOT NULL,
    Vagas INT,
    PRIMARY KEY (ID_Concurso, ID_Cargo),
    FOREIGN KEY (ID_Concurso) REFERENCES CONCURSO(ID_Concurso),
    FOREIGN KEY (ID_Cargo) REFERENCES CARGO(ID_Cargo)
);