
CREATE TABLE MARCA (
    ID_Marca INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE MODELO (
    ID_Modelo INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    ID_Marca INT NOT NULL,
    FOREIGN KEY (ID_Marca) REFERENCES MARCA(ID_Marca)
);

--
CREATE TABLE CATEGORIA (
    ID_Categoria INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL UNIQUE,
    Descricao TEXT
);


CREATE TABLE PESSOA (
    ID_Pessoa INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    CPF_CNPJ VARCHAR(14) UNIQUE,
    Endereco VARCHAR(255),
    Telefone VARCHAR(20)
);
CREATE TABLE VEICULO (
    Placa VARCHAR(8) PRIMARY KEY,
    AnoFabricacao INT,
    ID_Modelo INT NOT NULL,
    ID_Categoria INT NOT NULL,
    FOREIGN KEY (ID_Modelo) REFERENCES MODELO(ID_Modelo),
    FOREIGN KEY (ID_Categoria) REFERENCES CATEGORIA(ID_Categoria)
);

CREATE TABLE RESPONSABILIDADE (
    ID_Responsabilidade INT PRIMARY KEY AUTO_INCREMENT,
    DataInicio DATE NOT NULL,
    DataFim DATE,
    ID_Pessoa INT NOT NULL,
    Placa VARCHAR(8) NOT NULL,
    FOREIGN KEY (ID_Pessoa) REFERENCES PESSOA(ID_Pessoa),
    FOREIGN KEY (Placa) REFERENCES VEICULO(Placa)
);