CREATE TABLE ALMOXARIFADO (
    ID_Almoxarifado INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL UNIQUE,
    Endereco VARCHAR(255)
);

CREATE TABLE LINHA_PRODUTO (
    ID_Linha INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL UNIQUE,
    Descricao TEXT
);

CREATE TABLE PRODUTO (
    ID_Produto INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Descricao TEXT,
    ID_Linha INT NOT NULL,
    FOREIGN KEY (ID_Linha) REFERENCES LINHA_PRODUTO(ID_Linha)
);

CREATE TABLE FORNECEDOR (
    ID_Fornecedor INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    CNPJ VARCHAR(18) UNIQUE,
    Endereco VARCHAR(255),
    Telefone VARCHAR(20)
);

CREATE TABLE NOTA_FISCAL_COMPRA (
    ID_NF_Compra INT PRIMARY KEY AUTO_INCREMENT,
    Numero VARCHAR(20) NOT NULL UNIQUE,
    DataEmissao DATE NOT NULL,
    ValorTotal DECIMAL(10, 2),
    ID_Fornecedor INT NOT NULL,
    FOREIGN KEY (ID_Fornecedor) REFERENCES FORNECEDOR(ID_Fornecedor)
);

CREATE TABLE ITEM_NF_COMPRA (
    ID_Item_NF_Compra INT PRIMARY KEY AUTO_INCREMENT,
    Quantidade DECIMAL(10, 2) NOT NULL,
    ValorUnitario DECIMAL(10, 2) NOT NULL,
    ID_NF_Compra INT NOT NULL,
    ID_Produto INT NOT NULL,
    FOREIGN KEY (ID_NF_Compra) REFERENCES NOTA_FISCAL_COMPRA(ID_NF_Compra),
    FOREIGN KEY (ID_Produto) REFERENCES PRODUTO(ID_Produto)
);

CREATE TABLE CLIENTE (
    ID_Cliente INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    CPF_CNPJ VARCHAR(14) UNIQUE,
    Endereco VARCHAR(255),
    Telefone VARCHAR(20)
);

CREATE TABLE NOTA_FISCAL_VENDA (
    ID_NF_Venda INT PRIMARY KEY AUTO_INCREMENT,
    Numero VARCHAR(20) NOT NULL UNIQUE,
    DataEmissao DATE NOT NULL,
    ValorTotal DECIMAL(10, 2),
    ID_Cliente INT NOT NULL,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Cliente)
);

CREATE TABLE ITEM_NF_VENDA (
    ID_Item_NF_Venda INT PRIMARY KEY AUTO_INCREMENT,
    Quantidade DECIMAL(10, 2) NOT NULL,
    ValorUnitario DECIMAL(10, 2) NOT NULL,
    ID_NF_Venda INT NOT NULL,
    ID_Produto INT NOT NULL,
    FOREIGN KEY (ID_NF_Venda) REFERENCES NOTA_FISCAL_VENDA(ID_NF_Venda),
    FOREIGN KEY (ID_Produto) REFERENCES PRODUTO(ID_Produto)
);

CREATE TABLE ESTOQUE (
    ID_Estoque INT PRIMARY KEY AUTO_INCREMENT,
    Quantidade INT NOT NULL DEFAULT 0,
    ID_Produto INT NOT NULL,
    ID_Almoxarifado INT NOT NULL,
    UNIQUE (ID_Produto, ID_Almoxarifado),
    FOREIGN KEY (ID_Produto) REFERENCES PRODUTO(ID_Produto),
    FOREIGN KEY (ID_Almoxarifado) REFERENCES ALMOXARIFADO(ID_Almoxarifado)
