CREATE TABLE CIDADE (
    ID_Cidade INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL UNIQUE,
    UF VARCHAR(2) NOT NULL
);

CREATE TABLE FLORICULTURA (
    ID_Floricultura INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Endereco VARCHAR(255),
    Telefone VARCHAR(20)
);

CREATE TABLE CONVENIO (
    ID_Convenio INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL UNIQUE,
    Descricao TEXT
);

CREATE TABLE CLIENTE (
    ID_Cliente INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Endereco VARCHAR(255),
    Telefone VARCHAR(20),
    ID_Convenio INT,
    FOREIGN KEY (ID_Convenio) REFERENCES CONVENIO(ID_Convenio)
);

CREATE TABLE TIPO_FLOR (
    ID_TipoFlor INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL UNIQUE,
    Descricao TEXT
);

CREATE TABLE PEDIDO (
    ID_Pedido INT PRIMARY KEY AUTO_INCREMENT,
    DataPedido DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_Cliente INT NOT NULL,
    CidadeEntrega INT NOT NULL,
    ID_Floricultura INT,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Cliente),
    FOREIGN KEY (CidadeEntrega) REFERENCES CIDADE(ID_Cidade),
    FOREIGN KEY (ID_Floricultura) REFERENCES FLORICULTURA(ID_Floricultura)
);

CREATE TABLE ITEM_PEDIDO (
    ID_ItemPedido INT PRIMARY KEY AUTO_INCREMENT,
    ID_Pedido INT NOT NULL,
    ID_TipoFlor INT NOT NULL,
    Quantidade INT NOT NULL,
    Observacoes TEXT,
    FOREIGN KEY (ID_Pedido) REFERENCES PEDIDO(ID_Pedido),
    FOREIGN KEY (ID_TipoFlor) REFERENCES TIPO_FLOR(ID_TipoFlor)
);

CREATE TABLE ATENDIMENTO_CIDADE (
    ID_Floricultura INT NOT NULL,
    ID_Cidade INT NOT NULL,
    PRIMARY KEY (ID_Floricultura, ID_Cidade),
    FOREIGN KEY (ID_Floricultura) REFERENCES FLORICULTURA(ID_Floricultura),
    FOREIGN KEY (ID_Cidade) REFERENCES CIDADE(ID_Cidade)
);