CREATE TABLE CONVENIO (
    ID_Convenio INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL UNIQUE,
    Descricao TEXT
);

CREATE TABLE CLIENTE (
    ID_Cliente INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) UNIQUE,
    Endereco VARCHAR(255),
    Telefone VARCHAR(20),
    ID_Convenio INT,
    FOREIGN KEY (ID_Convenio) REFERENCES CONVENIO(ID_Convenio)
);

CREATE TABLE QUARTO (
    ID_Quarto INT PRIMARY KEY AUTO_INCREMENT,
    Numero VARCHAR(10) NOT NULL UNIQUE,
    Tipo ENUM('Luxo', 'Standard') NOT NULL,
    Capacidade INT
);

CREATE TABLE HOSPEDE (
    ID_Hospede INT PRIMARY KEY AUTO_INCREMENT,
    ID_Cliente INT NOT NULL,
    DataCheckIn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataCheckOut DATETIME,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Cliente)
);

CREATE TABLE ACOMODACAO (
    ID_Acomodacao INT PRIMARY KEY AUTO_INCREMENT,
    ID_Hospede INT NOT NULL,
    ID_Quarto INT NOT NULL,
    DataEntradaQuarto DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataSaidaQuarto DATETIME,
    FOREIGN KEY (ID_Hospede) REFERENCES HOSPEDE(ID_Hospede),
    FOREIGN KEY (ID_Quarto) REFERENCES QUARTO(ID_Quarto)
);

CREATE TABLE ITEM_CARDAPIO (
    ID_ItemCardapio INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Descricao TEXT,
    Preco DECIMAL(10, 2)
);

CREATE TABLE PEDIDO_COPA (
    ID_PedidoCopa INT PRIMARY KEY AUTO_INCREMENT,
    ID_Acomodacao INT NOT NULL,
    ID_ItemCardapio INT NOT NULL,
    DataPedido DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Quantidade INT NOT NULL DEFAULT 1,
    Observacoes TEXT,
    FOREIGN KEY (ID_Acomodacao) REFERENCES ACOMODACAO(ID_Acomodacao),
    FOREIGN KEY (ID_ItemCardapio) REFERENCES ITEM_CARDAPIO(ID_ItemCardapio)
);

CREATE TABLE SERVICO (
    ID_Servico INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL UNIQUE,
    Descricao TEXT,
    Preco DECIMAL(10, 2)
);

CREATE TABLE UTILIZACAO_SERVICO (
    ID_Utilizacao INT PRIMARY KEY AUTO_INCREMENT,
    ID_Acomodacao INT NOT NULL,
    ID_Servico INT NOT NULL,
    DataUtilizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Quantidade INT NOT NULL DEFAULT 1,
    Observacoes TEXT,
    FOREIGN KEY (ID_Acomodacao) REFERENCES ACOMODACAO(ID_Acomodacao),
    FOREIGN KEY (ID_Servico) REFERENCES SERVICO(ID_Servico)
);

CREATE TABLE RESERVA (
    ID_Reserva INT PRIMARY KEY AUTO_INCREMENT,
    ID_Cliente INT NOT NULL,
    DataReserva DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataCheckInPrevista DATE NOT NULL,
    DataCheckOutPrevista DATE NOT NULL,
    NumeroAdultos INT DEFAULT 1,
    NumeroCriancas INT DEFAULT 0,
    Observacoes TEXT,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Cliente)
);

CREATE TABLE RESERVA_QUARTO (
    ID_Reserva INT NOT NULL,
    ID_Quarto INT NOT NULL,
    PRIMARY KEY (ID_Reserva, ID_Quarto),
    FOREIGN KEY (ID_Reserva) REFERENCES RESERVA(ID_Reserva),
    FOREIGN KEY (ID_Quarto) REFERENCES QUARTO(ID_Quarto)
);